# This workflow automically updates Clustering Model every Quarter
name: Rider Clustering Quarterly Training

on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'  # At 00:00 on Jan, Apr, Jul, Oct 1st
  workflow_dispatch:

jobs:
  run-pipeline-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create .env file
        run: |
          echo "REDASH_BASE_URL=${{ secrets.REDASH_BASE_URL }}" >> .env
          echo "REDASH_API_KEY=${{ secrets.REDASH_API_KEY }}" >> .env

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run clustering pipeline
        run: python -m utils.pipeline

      - name: Commit and push updated model files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add models/*.csv models/*.pkl
          git commit -m "[Automated] Quarterly model update $(date +'%Y-%m-%d')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
