name: Weekly Rider Clustering

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  run-weekly-clustering:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment
        run: |
          echo "REDASH_API_KEY=${{ secrets.REDASH_API_KEY }}" >> .env
          echo "REDASH_URL=${{ secrets.REDASH_URL }}" >> .env
          echo "SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}" >> .env
          echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> .env

      - name: Run clustering script
        run: python weekly/rider_clustering_w.py
